### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by ssoonmi** [ZackSyed/Itadaki#2]
- [x] format like the example given (wrap code in backticks, ``, e.g. `user_id`)
- [x] should show indexing at the bottom of every table, (e.g. index on `[user_id, channel_id], unique: true`)
- [x] should show which table any foreign key column references, (e.g. `author_id` references `users`)
- [x] keep wording convention of table names consistent
---
`users`
- [x] `username` should be unique
- why do you need `debt` to be defined on the table itself?
---
`checks`
- why is `name` indexed?
- [x] instead of `your_split`, shouldn't the column be named something like `amount`? The `split` should be covered by the `splits` table.
---
`restaurants`
- ~~I would hold off from having a `location` on a `restaurant` for now, especially if you are not going to be using it to complete your MVP's~~
- [x] change `location` to `longitude` and `latitude`
---
`comments`
- [x] `comments` also need to belong to whatever relation a `user` can `comment` on. (e.g. if `users` can comment on a `check`, then there needs to be a `check_id` on the `comments` table)
---
`groups`
- [x] can a `group` have multiple `checks`? If not, you can combine `checks` and `groups` tables. If so, then no need to have `opener_id` on `groups`.
---
`friends`
- why do you need the `IOU` and `UOME` saved to your database?
- [x] probably want a column on here that says if a `friend` has accepted/not accepted yet a friend request from another `user`
---
`splits`
- [x] don't need `group_id` because can access its `group` through `checks` association
- [x] same with `restaurant_id`
- why do you have `friend_id` here?
- [x] should have the actual `split` amount owed as a column
---

Still needs a bit of work but getting there! Try to have most of these changes by tomorrow (1/17). If you need help on thinking about how to structure your database, then Slack me and we can determine a time to talk about it!
If you don't think some of these suggestions are appropriate, please comment below!

**Comment by ZackSyed** [comment]
I want to keep restaurant locations in the scheme, because I would like to add a feature that maps out checks to their origin location (restaurant). A user can see where he spent money. 

Groups should be allowed to create new checks, and split money accordingly. This will be another feature on my app.

**Comment by ssoonmi** [comment]
Okay! that's fine. I think it's better to have `latitude` and `longitude` columns instead of `location`, though. Because that's what you use to map the restaurant.

**Comment by ssoonmi** [comment]
Can you keep the wording for table name headers consistent?

**Comment by ZackSyed** [comment]
Yep, fixed both problems. Thanks for the heads up on the location strings. Fixed that. Will reflect it on my state.
