### ISSUE TITLE
Database Schema II

### ISSUE THREAD

**Issue by ssoonmi** [ZackSyed/Itadaki#3]
- [x] index on all foreign keys
---
`users`
- [x] index on `username` and `email` should be separate (since there has to be both unique `usernames` and `emails`)
- [x] `debt` isn't a table so it shouldn't be an association
   - A `user` should have `debt` from multiple sources (addition of `amount_owed` through the `splits` table)
---
`restaurants`
- [x] should have an index on `latitude` and `longitude` also since you will probably be searching by them
---
`friends`
- [x] should only have one `friend` relation between one `user` to another `user` existing on the table (make a uniqueness constraint)
--- 
`groups`
- [x] need to have a join table between `groups` and `users` because a `group` can have many `users` and a `user` can have many `groups`

**Comment by ZackSyed** [comment]
would indexing on all foreign keys be too heavy for the database?

**Comment by ZackSyed** [comment]
Im not sure if the Tabs table should hold a reference to the user?

**Comment by ZackSyed** [comment]
should friends hold a reference to group_id, or should i put that in users or is this a use case for the polymorphic association

**Comment by ssoonmi** [comment]
> would indexing on all foreign keys be too heavy for the database?

No, you usually want to index foreign keys. 
---

> Im not sure if the Tabs table should hold a reference to the user?

Yeah I don't think so either since you can get all the participants from the `group` that the `tab` is part of. Unless you have only certain participants from a `group` in a `tab`, not all.
---


> should friends hold a reference to group_id, or should i put that in users or is this a use case for the polymorphic association
> or make the join table for group and users?

Friends should be under `users` and the `group` should just have a reference to all the participants in the `group`. 
And yes I think you should have a join table for `groups` and `users` since `users` can belong to many `groups` and a `group` has many `users` as participants.
---

**Comment by ZackSyed** [comment]
added the group table

**Comment by ZackSyed** [comment]
group join table
