### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ssoonmi** [ZackSyed/Itadaki#4]
`tabs`
- [x] Hold a reference to all the `splits` for a `tab` (e.g. `splitIds`)
- [x] Hold a reference to all the `comments` on a tab
- [x] Total amount owed
---
`users`
- [x] Hold a reference to all the `tabs` for the current `user`
- [x] Hold a reference to all the `splits` for the current `user`
- [x] instead of having a separate `friends` slice of state, store `friend_ids` on the current `user`
---
`groups`
- [x] Hold a reference to all the `tabs` for a `group`
---
`splits`
- [x] Need a `splits` slice of state
---

Nice job!

**Comment by ZackSyed** [comment]
I would get the total amount owed from the split table, i dont have it on my tabs table. 
or would i be able to extract that data and send it up.

**Comment by ssoonmi** [comment]
Exactly. You would extract that data from an association and send it up with the tabs.
