### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by ssoonmi** [ZackSyed/Itadaki#5]
## Backend Routes
- [x] api backend routes should fetch/return data, not display anything
---
`tabs`
- [x] posting a `tab` needs `group_id` in the route path
---
`splits`
- [x] do you need routes for creating a split?
---
`restaurants`
- [x] third route should be `/api/tabs/:tab_id/restaurants/new`
---
`comments`
- [x] second routes should be `/api/user_id/tab_id/comment/new`
---

### Frontend Routes
- [x] Please make it look like the example
---
Nice job!

**Comment by ZackSyed** [comment]
uhm do i??????

**Comment by ZackSyed** [comment]
make it look all nice and pretty

**Comment by ssoonmi** [comment]
`tabs`
Make sure you specify the keyword `groups` before the wildcard `group_id` inside of the `tabs` nested route!

**Comment by ssoonmi** [comment]
- [ ] `tabs`
- [ ] `comments`
- [ ] `splits`
