### ISSUE TITLE
Sample State II

### ISSUE THREAD

**Issue by ssoonmi** [ZackSyed/Itadaki#6]
`users`
- [x] should still have a `users` slice of state. `current_user` will be known through extracting the `currentUserId` from the `session` slice of state and keying into the `users`. `users` should store `friends`' names and other `users` that are necessary to display `group` participants, `commenters`, etc.
---
`splits`
- [x] should be under `entities`
---

**Comment by ZackSyed** [comment]
I probably should add groups now

**Comment by ssoonmi** [comment]
- [ ] get rid of `interactions` slice of state
