### ISSUE TITLE
Database Schema III

### ISSUE THREAD

**Issue by ssoonmi** [ZackSyed/Itadaki#7]
`groups`
- [x] don't think you need `participant_id` if you have the `interactions` join table
---
`interactions`
- [x] may want to make the combination of a `user` to a `group` unique

**Comment by ZackSyed** [comment]
feels like I'm finally getting to the bigger picture

**Comment by ssoonmi** [comment]
- [ ] still need to delete all references to `participant_id` in `groups` table
